import 'package:flutter/material.dart';

class LudoBoard extends StatelessWidget {
  const LudoBoard({super.key});
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title:Center(child:Text("LUDO BOARD" 
      ,style: TextStyle(color: Colors.white,fontSize: 22),),),
      backgroundColor:Colors.black ,),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            // Row 1
            Row(mainAxisAlignment: MainAxisAlignment.center,
              children: [
                Container(width: 30, height: 30, color: Colors.lightGreenAccent,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.lightGreenAccent,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.lightGreenAccent,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.lightGreenAccent,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.lightGreenAccent,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.lightGreenAccent,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.white,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.white,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.white,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: const Color.fromARGB(255, 250, 250, 168),child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: const Color.fromARGB(255, 254, 254, 173),child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: const Color.fromARGB(255, 253, 253, 173),child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: const Color.fromARGB(255, 247, 247, 166),child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: const Color.fromARGB(255, 252, 252, 169),child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: const Color.fromARGB(255, 247, 247, 166),child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
              ],
            ),

            // Row 2
            Row(mainAxisAlignment: MainAxisAlignment.center,
              children: [
                Container(width: 30, height: 30, color: Colors.lightGreenAccent,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.green,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.green,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.green,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.green,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.lightGreenAccent,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.white,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.yellow,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.yellow,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: const Color.fromARGB(255, 252, 252, 169),child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.yellow,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.yellow,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.yellow,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.yellow,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: const Color.fromARGB(255, 251, 251, 167),child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
              ],
            ),
// row3
  Row(mainAxisAlignment: MainAxisAlignment.center,
              children: [
                Container(width: 30, height: 30, color: Colors.lightGreenAccent,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.green,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.white,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.white,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.green,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.lightGreenAccent,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: const Color.fromARGB(255, 73, 73, 73),child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.yellow,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.white,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: const Color.fromARGB(255, 253, 253, 172),child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.yellow,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.white,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.white,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.yellow,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: const Color.fromARGB(255, 253, 253, 170),child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
              ],
            ),

            // row4
           Row(mainAxisAlignment: MainAxisAlignment.center,
              children: [
                Container(width: 30, height: 30, color: Colors.lightGreenAccent,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.green,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.white,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.white,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.green,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.lightGreenAccent,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.white,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.yellow,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.white,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: const Color.fromARGB(255, 252, 252, 168),child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.yellow,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.white,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.white,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.yellow,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: const Color.fromARGB(255, 253, 253, 169),child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
              ],
            ),

            // row5
            Row(mainAxisAlignment: MainAxisAlignment.center,
              children: [
                Container(width: 30, height: 30, color: Colors.lightGreenAccent,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.green,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.green,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.green,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.green,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.lightGreenAccent,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.white,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.yellow,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.white,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: const Color.fromARGB(255, 254, 254, 170),child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.yellow,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.yellow,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.yellow,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.yellow,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: const Color.fromARGB(255, 249, 249, 168),child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
              ],
            ),

            // row6
             Row(mainAxisAlignment: MainAxisAlignment.center,
              children: [
                Container(width: 30, height: 30, color: Colors.lightGreenAccent,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.lightGreenAccent,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.lightGreenAccent,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.lightGreenAccent,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.lightGreenAccent,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.lightGreenAccent,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.white,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.yellow,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.white,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: const Color.fromARGB(255, 252, 252, 171),child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: const Color.fromARGB(255, 245, 245, 164),child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: const Color.fromARGB(255, 254, 254, 170),child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: const Color.fromARGB(255, 254, 254, 174),child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: const Color.fromARGB(255, 255, 255, 171),child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: const Color.fromARGB(255, 255, 255, 171),child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
              ],
            ),
            //  row7
              Row(mainAxisAlignment: MainAxisAlignment.center,
              children: [
                Container(width: 30, height: 30, color: Colors.white,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.green,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.white,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.white,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.white,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.white,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.yellow,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.yellow,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.yellow,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.white,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.white,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.white,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: const Color.fromARGB(255, 73, 73, 73),child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.white,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.white,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
              ],
            ),

            // row8
            Row(mainAxisAlignment: MainAxisAlignment.center,
              children: [
                Container(width: 30, height: 30, color: Colors.white,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.green,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.green,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.green,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.green,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.green,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.orangeAccent,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.orangeAccent,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.orangeAccent,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.blue,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.blue,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.blue,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.blue,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.blue,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.white,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
              ],
            ),
            // row9
             Row(mainAxisAlignment: MainAxisAlignment.center,
              children: [
                Container(width: 30, height: 30, color: Colors.white,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.white,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: const Color.fromARGB(255, 73, 73, 73),child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.white,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.white,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.white,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.red,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.red,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.red,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.white,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.white,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.white,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.white,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.blue,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.white,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
              ],
            ),
// row10
 Row(mainAxisAlignment: MainAxisAlignment.center,
              children: [
                Container(width: 30, height: 30, color: const Color.fromARGB(255, 252, 126, 126),child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: const Color.fromARGB(255, 252, 124, 124),child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: const Color.fromARGB(255, 250, 125, 125),child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: const Color.fromARGB(255, 252, 125, 125),child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: const Color.fromARGB(255, 252, 124, 124),child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: const Color.fromARGB(255, 252, 122, 122),child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.white,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.red,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.white,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: const Color.fromARGB(255, 128, 214, 254),child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: const Color.fromARGB(255, 128, 213, 252),child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: const Color.fromARGB(255, 127, 214, 254),child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: const Color.fromARGB(255, 129, 214, 253),child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: const Color.fromARGB(255, 126, 213, 254),child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: const Color.fromARGB(255, 125, 211, 251),child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
              ],
            ),

// row11
 Row(mainAxisAlignment: MainAxisAlignment.center,
              children: [
                Container(width: 30, height: 30, color: const Color.fromARGB(255, 255, 129, 129),child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.red,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.red,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.red,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.red,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: const Color.fromARGB(255, 254, 129, 129),child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.white,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.red,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.white,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: const Color.fromARGB(255, 126, 211, 250),child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.blue,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.blue,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.blue,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.blue,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: const Color.fromARGB(255, 127, 214, 254),child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
              ],
            ),

            // row12
             Row(mainAxisAlignment: MainAxisAlignment.center,
              children: [
                Container(width: 30, height: 30, color: const Color.fromARGB(255, 253, 138, 138),child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.red,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.white,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.white,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.red,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: const Color.fromARGB(255, 252, 134, 134),child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.white,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.red,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.white,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: const Color.fromARGB(255, 126, 213, 254),child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.blue,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.white,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.white,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.blue,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: const Color.fromARGB(255, 128, 214, 254),child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
              ],
            ),
            // row13
             Row(mainAxisAlignment: MainAxisAlignment.center,
              children: [
                Container(width: 30, height: 30, color: const Color.fromARGB(255, 250, 127, 127),child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.red,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.white,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.white,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.red,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: const Color.fromARGB(255, 252, 127, 127),child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.white,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.red,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: const Color.fromARGB(255, 73, 73, 73),child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: const Color.fromARGB(255, 127, 211, 250),child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.blue,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.white,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.white,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.blue,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                 Container(width: 30, height: 30, color: const Color.fromARGB(255, 125, 210, 249),child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
              ],
            ),
            // row14
             Row(mainAxisAlignment: MainAxisAlignment.center,
              children: [
                Container(width: 30, height: 30, color: const Color.fromARGB(255, 252, 126, 126),child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.red,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.red,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.red,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.red,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: const Color.fromARGB(255, 253, 127, 127),child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.red,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.red,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.white,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: const Color.fromARGB(255, 131, 212, 249),child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.blue,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.blue,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.blue,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.blue,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: const Color.fromARGB(255, 133, 216, 254),child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
              ],
            ),
            // row15
             Row(mainAxisAlignment: MainAxisAlignment.center,
              children: [
                
                Container(width: 30, height: 30, color: const Color.fromARGB(255, 255, 129, 129),child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: const Color.fromARGB(255, 255, 133, 133),child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: const Color.fromARGB(255, 250, 129, 129),child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: const Color.fromARGB(255, 253, 131, 131),child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: const Color.fromARGB(255, 254, 129, 129),child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: const Color.fromARGB(255, 254, 129, 129),child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.white,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.white,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: Colors.white,child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: const Color.fromARGB(255, 124, 211, 252),child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: const Color.fromARGB(255, 124, 211, 252),child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: const Color.fromARGB(255, 124, 211, 252),child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: const Color.fromARGB(255, 124, 211, 252),child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: const Color.fromARGB(255, 124, 211, 252),child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
                Container(width: 30, height: 30, color: const Color.fromARGB(255, 124, 211, 252), child:DecoratedBox(decoration:BoxDecoration(border :BoxBorder.all(color: Colors.black,width: 1))),),
              ],
            ),


          ],
        ),
      ),
    );
  }
}
